apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartKind: pages
    chartRepository: https://github.com/jenkins-x-bdd/repo.git
    clusterName: microfinance-k3s
    environmentGitOwner: arunnattarayan
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: k3s
    registry: ghcr.io
  environments:
  - key: dev
    owner: arunnattarayan
    repository: jx-template
  - key: staging
  ingress:
    domain: 35.223.51.193.nip.io
    ignoreLoadBalancer: true
    kind: ingress
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  pipelineUser:
    username: arunnattarayan
  repository: bucketrepo
  secretStorage: local
  vault: {}
  webhook: lighthouse
