apiVersion: v1
data:
  plugins.yaml: |
    approve:
    - lgtm_acts_as_approve: true
      repos:
      - arunnattarayan/jx-template
      require_self_approval: true
    - lgtm_acts_as_approve: true
      repos:
      - arunnattarayan/go-test
      require_self_approval: true
    cat: {}
    cherry_pick_unapproved: {}
    config_updater:
      gzip: false
      maps:
        env/prow/job.yaml:
          name: config
        env/prow/plugins.yaml:
          name: plugins
    external_plugins:
      arunnattarayan/go-test:
      - endpoint: http://cd-indicators.jx.svc.cluster.local/lighthouse/events
        name: cd-indicators
      - endpoint: http://lighthouse-webui-plugin.jx.svc.cluster.local/lighthouse/events
        name: lighthouse-webui-plugin
      arunnattarayan/jx-template:
      - endpoint: http://cd-indicators.jx.svc.cluster.local/lighthouse/events
        name: cd-indicators
      - endpoint: http://lighthouse-webui-plugin.jx.svc.cluster.local/lighthouse/events
        name: lighthouse-webui-plugin
    label:
      additional_labels: null
    owners: {}
    plugins:
      arunnattarayan/go-test:
      - approve
      - assign
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - cat
      - dog
      - pony
      arunnattarayan/jx-template:
      - config-updater
      - approve
      - assign
      - help
      - hold
      - lgtm
      - lifecycle
      - override
      - size
      - trigger
      - wip
      - cat
      - dog
      - pony
    requiresig: {}
    sigmention: {}
    size:
      l: 0
      m: 0
      s: 0
      xl: 0
      xxl: 0
    triggers:
    - repos:
      - arunnattarayan/jx-template
      trusted_org: arunnattarayan
    - repos:
      - arunnattarayan/go-test
      trusted_org: arunnattarayan
    welcome:
    - message_template: Welcome
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: plugins
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
